# Generated by Django 4.0 on 2021-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='c/img/'),
        ),
    ]
